version: 2.1

aliases:
  - &restore-node-modules-cache
    name: Restore node_modules cache
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    name: Save yarn cache
    paths:
      - ~/.cache/yarn
    key: v1-yarn-cache

  - &save-node-modules-cache
    name: Save node_modules cache
    paths:
      - node_modules
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

defaults: &defaults
  docker:
    - image: circleci/node:12.22.7-bullseye-browsers-legacy
  working_directory: ~/caffeine-api

jobs:
  build_packages:
    <<: *defaults

    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Build Packages
          command: yarn build

      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'

  lint_test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/caffeine-api

      - run:
          name: Run Lint
          command: yarn lint

  unit_test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/caffeine-api

      - run:
          name: Run Unit Tests
          command: yarn test:ci

workflows:
  branch-workflow:
    jobs:
      - build_packages
      - lint_test:
          requires:
            - build_packages
      - unit_test:
          requires:
            - build_packages
