version: 2.1

parameters:
  is_pr:
    type: boolean
    default: false

aliases:
  - &restore-node-modules-cache
    name: Restore node_modules cache
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    name: Save yarn cache
    paths:
      - ~/.cache/yarn
    key: v1-yarn-cache

  - &save-node-modules-cache
    name: Save node_modules cache
    paths:
      - node_modules
    key: v1-yarn-deps-{{ checksum "yarn.lock" }}

defaults: &defaults
  docker:
    - image: cimg/node:18.17.0
  working_directory: ~/caffeine-api

jobs:
  install_dependencies:
    <<: *defaults

    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'

  lint_test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/caffeine-api

      - run:
          name: Run Lint
          command: yarn lint

  unit_test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/caffeine-api

      - run:
          name: Run Unit Tests
          command: yarn test:ci

workflows:
  pr-workflow:
    when: << pipeline.parameters.is_pr >>
    jobs:
      - install_dependencies
      - lint_test:
          requires:
            - install_dependencies
      - unit_test:
          requires:
            - install_dependencies
